'\" t
.\"     Title: keyholder-auth
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 02/17/2017
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "KEYHOLDER\-AUTH" "1" "02/17/2017" "\ \&" "\ \&"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
keyholder-auth \- ssh key authorizations for keyholder\*(Aqs ssh\-agent\-proxy\&.
.SH "DESCRIPTION"
.sp
Keyholder authorizes users based on unix group membership\&. To give a certain group of users access to one or more of the keyholder\-managed ssh keys, you must create an authorization yaml file in \fB/etc/keyholder\-auth\&.d/\fR\&. An authorization file should contain a top level map with unix group names as keys, each mapped to a list of the ssh keys which that group is allowed to use\&.
.sp
For each ssh key name you must create a ssh private key \fB[key\-name]\fR and corresponding public key \fB[key\-name]\&.pub\fR in \fB/etc/keyholder\&.d/[key\-name]\fR\&.
.if n \{\
.sp
.\}
.RS 4
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
\fBImportant\fR
.ps -1
.br
.sp
Key files should be readable only by the keyholder daemon\(cqs uid\&.
.sp .5v
.RE
.SH "EXAMPLE"
.PP
\fBgroups.yaml\fR. 
.sp
.if n \{\
.RS 4
.\}
.nf
# map unix groups to ssh keys in /etc/keyholder\&.d:
\-\-\-
users: [users\-key]
admins: [users\-key, admins\-key]
.fi
.if n \{\
.RE
.\}
.sp
.SH "SEE ALSO"
.sp
keyholder(1), ssh\-agent\-proxy(1)
.SH "RESOURCES"
.sp
Source: https://phabricator\&.wikimedia\&.org/source/keyholder/
.SH "COPYING"
.sp
Keyholder is licensed under the terms of the Apache License, Version 2\&.0
.sp
Copyright 2015\-2017 by Wikimedia Foundation, Inc and Contributors\&.
