'\" t
.\"     Title: ssh-agent-proxy
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 02/17/2017
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "SSH\-AGENT\-PROXY" "1" "02/17/2017" "\ \&" "\ \&"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
ssh-agent-proxy \- filtering proxy for ssh\-agent
.SH "SYNOPSIS"
.sp
ssh\-agent\-proxy [\-\-bind ADDRESS] [\-\-connect ADDRESS] [\-\-auth\-dir DIR]
.SH "DESCRIPTION"
.sp
Creates a UNIX domain socket that proxies connections to an ssh\-agent(1) socket, disallowing any operations except listing identities and signing requests\&. Request signing is only permitted if group is allowed to use the requested public key fingerprint\&.
.SH "OPTIONS"
.sp
\fB\-\-bind\fR ADDRESS Bind the proxy to the UNIX domain socket at this address (default: \fI/run/keyholder/proxy\&.sock\fR)\&.
.sp
\fB\-\-connect\fR ADDRESS Proxy connects to the ssh\-agent socket at this address (default: \fI/run/keyholder/agent\&.sock\fR)\&.
.sp
\fB\-\-auth\-dir\fR DIR Directory where YAML files containing group:[key(s)] access can be found (default: \fI/etc/keyholder\-auth\&.d\fR)\&.
.SH "SEE ALSO"
.sp
keyholder(1), keyholder\-auth(1)
.SH "RESOURCES"
.sp
Source: https://phabricator\&.wikimedia\&.org/source/keyholder/
.SH "COPYING"
.sp
Keyholder is licensed under the terms of the Apache License, Version 2\&.0
.sp
Copyright 2015\-2017 by Wikimedia Foundation, Inc and Contributors\&.
