:lang: en

= ssh-agent-proxy(1)
:doctype: manpage

== NAME

ssh-agent-proxy - filtering proxy for ssh-agent

== SYNOPSIS
ssh-agent-proxy [--bind ADDRESS] [--connect ADDRESS] [--auth-dir DIR]

== DESCRIPTION
Creates a UNIX domain socket that proxies connections to an ssh-agent(1)
socket, disallowing any operations except listing identities and signing
requests. Request signing is only permitted if group is allowed to use
the requested public key fingerprint.

== OPTIONS

*--bind* ADDRESS    Bind the proxy to the UNIX domain socket at this address
                  (default: '/run/keyholder/proxy.sock').

*--connect* ADDRESS Proxy connects to the ssh-agent socket at this address
                  (default: '/run/keyholder/agent.sock').

*--auth-dir* DIR    Directory where YAML files containing group:[key(s)]
                  access can be found (default: '/etc/keyholder-auth.d').

== SEE ALSO
keyholder(1)

== RESOURCES

github: <https://github.com/wikimedia/keyholder>

== COPYING

Copyright 2015-2017 by Wikimedia Foundation, Inc and Contributors.